
title: Learn to Code LA
date: September 14, 2016
num_photos: 3

exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - create-zip.js
  - LICENSE
  - CNAME
  - README.md

keep_files:
  - .git
  - .gitignore
  - .nojekyll
  - CNAME
  - README.md
